#!/usr/bin/python

import RPi.GPIO as GPIO
import sys, os, re, time, fcntl
import smbus as smbus

fd = sys.stdin.fileno()
fl = fcntl.fcntl(fd, fcntl.F_GETFL)
fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)

GPIO.setmode(GPIO.BOARD)
dtr = re.compile('.+TIOCM_DTR.+')
start = time.time()

# I2C setup
i2c_addr = 0x20
i2c = smbus.SMBus(1)
reset   = 0x08ff  # P13=Prog_RESET_Ardu
nominal = 0x10ff  # P14=Luefter_Rasp

def reset():
  i2c.write_byte_data(i2c_addr, reset & 0xff, (reset >> 8) & 0xff)
  time.sleep(0.12)
  i2c.write_byte_data(i2c_addr, nominal & 0xff, (nominal >> 8) & 0xff)

def process():
  while True:
    try: 
      duration = time.time() - start
      input = sys.stdin.readline().strip()
      if dtr.match(input):
        reset()
        return
      elif duration > 5000:
        return
    except:
      continue

process()
print "done with autoreset"
